/**
 * 상품 ID → 프로젝트 탭 쇼케이스 설정
 * productKey: 'modelia' | 'frontend' | 'backend' | 'image' | 'management' | 'infrastructure' | 'security' | 'documents'
 * techKey: product.showcase.tech[techKey] 로 표시명 조회 (3국어)
 * demoImageUrl: (image 카테고리만) 데모 결과 이미지 URL. 없으면 플레이스홀더 표시. 나중에 이미지 추가 시 여기만 교체.
 */
const SHOWCASE_CONFIG = {
  3: { productKey: 'frontend', techKey: 'javascript' },
  4: { productKey: 'frontend', techKey: 'typescript' },
  5: { productKey: 'frontend', techKey: 'react' },
  6: { productKey: 'frontend', techKey: 'vue' },
  7: { productKey: 'frontend', techKey: 'next' },
  8: { productKey: 'frontend', techKey: 'angular' },
  9: { productKey: 'frontend', techKey: 'svelte' },
  10: { productKey: 'frontend', techKey: 'jquery' },
  11: { productKey: 'frontend', techKey: 'webcomponents' },
  12: { productKey: 'frontend', techKey: 'nuxt' },
  13: { productKey: 'backend', techKey: 'node' },
  14: { productKey: 'backend', techKey: 'django' },
  15: { productKey: 'backend', techKey: 'spring' },
  16: { productKey: 'backend', techKey: 'go' },
  17: { productKey: 'backend', techKey: 'rust' },
  18: { productKey: 'backend', techKey: 'laravel' },
  19: { productKey: 'backend', techKey: 'rails' },
  20: { productKey: 'backend', techKey: 'dotnet' },
  21: { productKey: 'backend', techKey: 'kotlin' },
  22: { productKey: 'backend', techKey: 'scala' },
  23: { productKey: 'image', techKey: 'illustration', demoImageUrl: null },
  24: { productKey: 'image', techKey: 'pixel', demoImageUrl: null },
  25: { productKey: 'image', techKey: 'landscape', demoImageUrl: null },
  26: { productKey: 'modelia', techKey: null }, // 전용 쇼케이스 (3D 데모)
  27: { productKey: 'image', techKey: 'animation', demoImageUrl: null },
  28: { productKey: 'image', techKey: 'logo', demoImageUrl: null },
  29: { productKey: 'image', techKey: 'character', demoImageUrl: null },
  30: { productKey: 'image', techKey: 'uiux', demoImageUrl: null },
  31: { productKey: 'image', techKey: 'icon', demoImageUrl: null },
  32: { productKey: 'image', techKey: 'texture', demoImageUrl: null },
  33: { productKey: 'management', techKey: 'planning' },
  34: { productKey: 'management', techKey: 'task' },
  35: { productKey: 'management', techKey: 'merge' },
  36: { productKey: 'management', techKey: 'req' },
  37: { productKey: 'management', techKey: 'arch' },
  38: { productKey: 'management', techKey: 'quality' },
  39: { productKey: 'management', techKey: 'agile' },
  40: { productKey: 'management', techKey: 'scrum' },
  41: { productKey: 'management', techKey: 'po' },
  42: { productKey: 'management', techKey: 'techlead' },
  43: { productKey: 'infrastructure', techKey: 'docker' },
  44: { productKey: 'infrastructure', techKey: 'cloudflare' },
  45: { productKey: 'infrastructure', techKey: 'fly' },
  46: { productKey: 'infrastructure', techKey: 'aws' },
  47: { productKey: 'infrastructure', techKey: 'gcp' },
  48: { productKey: 'infrastructure', techKey: 'k8s' },
  49: { productKey: 'infrastructure', techKey: 'azure' },
  50: { productKey: 'infrastructure', techKey: 'terraform' },
  51: { productKey: 'infrastructure', techKey: 'cicd' },
  52: { productKey: 'infrastructure', techKey: 'monitor' },
  53: { productKey: 'security', techKey: 'audit' },
  54: { productKey: 'security', techKey: 'access' },
  55: { productKey: 'security', techKey: 'crypto' },
  56: { productKey: 'security', techKey: 'vuln' },
  57: { productKey: 'security', techKey: 'log' },
  58: { productKey: 'security', techKey: 'network' },
  59: { productKey: 'security', techKey: 'pentest' },
  60: { productKey: 'security', techKey: 'firewall' },
  61: { productKey: 'security', techKey: 'ids' },
  62: { productKey: 'security', techKey: 'compliance' },
  63: { productKey: 'documents', techKey: 'excel' },
  64: { productKey: 'documents', techKey: 'ppt' },
  65: { productKey: 'documents', techKey: 'github_doc' },
  66: { productKey: 'documents', techKey: 'word' },
  67: { productKey: 'documents', techKey: 'notion' },
  68: { productKey: 'documents', techKey: 'mail' },
  69: { productKey: 'documents', techKey: 'confluence' },
  70: { productKey: 'documents', techKey: 'markdown' },
  71: { productKey: 'documents', techKey: 'api_doc' },
  72: { productKey: 'documents', techKey: 'tech_writer' },
  73: { productKey: 'frontend', techKey: 'remix' },
  74: { productKey: 'frontend', techKey: 'solid' },
  75: { productKey: 'backend', techKey: 'nest' },
  76: { productKey: 'backend', techKey: 'fastapi' },
  77: { productKey: 'image', techKey: 'midjourney', demoImageUrl: null },
  78: { productKey: 'image', techKey: 'dalle', demoImageUrl: null },
  79: { productKey: 'infrastructure', techKey: 'devops' },
  80: { productKey: 'infrastructure', techKey: 'data' },
  81: { productKey: 'infrastructure', techKey: 'vercel' },
  82: { productKey: 'infrastructure', techKey: 'netlify' },
  83: { productKey: 'security', techKey: 'zerotrust' },
  84: { productKey: 'security', techKey: 'threat' },
  85: { productKey: 'documents', techKey: 'figma_doc' },
  86: { productKey: 'documents', techKey: 'swagger' },
};

export function getShowcaseConfig(productId) {
  const id = typeof productId === 'string' ? parseInt(productId, 10) : productId;
  return SHOWCASE_CONFIG[id] || null;
}

export function hasShowcase(productId) {
  return getShowcaseConfig(productId) != null;
}
