export const mockOrderStats = {
  totalOrders: 28,
  thisMonth: 896000,
  completed: 26,
  pending: 2,
  avgOrderValue: 32000,
};

export const mockOrders = [
  {
    id: 1234,
    orderId: '#1234',
    productName: 'MidjourneyAI',
    productIcon: '🎨',
    buyerName: 'John Doe',
    buyerEmail: 'john@example.com',
    amount: 32000,
    status: 'completed',
    date: '2024-12-08',
  },
  {
    id: 1235,
    orderId: '#1235',
    productName: 'Artelia',
    productIcon: '🖼️',
    buyerName: 'Sarah Miller',
    buyerEmail: 'sarah@example.com',
    amount: 30000,
    status: 'completed',
    date: '2024-12-07',
  },
  {
    id: 1236,
    orderId: '#1236',
    productName: 'Reacton',
    productIcon: '⚛️',
    buyerName: 'Mike Johnson',
    buyerEmail: 'mike@example.com',
    amount: 25000,
    status: 'pending',
    date: '2024-12-07',
  },
  {
    id: 1237,
    orderId: '#1237',
    productName: 'VueJin',
    productIcon: '🔒',
    buyerName: 'Emily Chen',
    buyerEmail: 'emily@example.com',
    amount: 28000,
    status: 'completed',
    date: '2024-12-06',
  },
  {
    id: 1238,
    orderId: '#1238',
    productName: 'Nexty',
    productIcon: '📊',
    buyerName: 'David Park',
    buyerEmail: 'david@example.com',
    amount: 35000,
    status: 'completed',
    date: '2024-12-06',
  },
  {
    id: 1239,
    orderId: '#1239',
    productName: 'MidjourneyAI',
    productIcon: '🎨',
    buyerName: 'Lisa Wong',
    buyerEmail: 'lisa@example.com',
    amount: 32000,
    status: 'completed',
    date: '2024-12-05',
  },
  {
    id: 1240,
    orderId: '#1240',
    productName: 'Artelia',
    productIcon: '🖼️',
    buyerName: 'Tom Anderson',
    buyerEmail: 'tom@example.com',
    amount: 30000,
    status: 'pending',
    date: '2024-12-05',
  },
  {
    id: 1241,
    orderId: '#1241',
    productName: 'Reacton',
    productIcon: '⚛️',
    buyerName: 'Anna Kim',
    buyerEmail: 'anna@example.com',
    amount: 25000,
    status: 'completed',
    date: '2024-12-04',
  },
];

export const mockProductOptions = [
  'MidjourneyAI',
  'Artelia',
  'Reacton',
  'VueJin',
  'Nexty',
];


